### ISSUE TITLE
Incorrect error handling (CodaClient.py)

### ISSUE THREAD

**Issue by ghost** [CodaProtocol/coda-python-client#11]
There are cases in which code 200 is returned, but the operation is not successfully completed. See an example below:
On my node i imported the wallet with command `coda advanced unsafe-import -privkey-path ~/keys/my-wallet`
I checked that it was correctly added
```
import CodaClient

node = CodaClient.Client(graphql_host="localhost", graphql_port="3085")
wallets = node.get_wallets()["ownedWallets"]
print(wallets)
```
Output: `{'ownedWallets': [{'publicKey': 'tdNDjfWWKZALACQPCLFaTGoAtdDoWEXeNuYRZZWChC4wbSeUb5tVn3UiSsVKt913A7btERefMS4GoEMkQWTs4TsGh21as6ecNP2HKfW6foxmXhwscDKdUEXqZRkCXJvNfz8wBjNXJcHaoK', 'balance': {'total': '1000'}}]}`

But if i try to send some coda (method `send_payment()`), it's return `None` and won't show me a error. Because the status will be 200
The error looks like this:
`{"errors":[{"message":"Couldn't find an unlocked key for specified `sender`. Did you unlock the account you're making a payment from?","path":["sendPayment"]}],"data":null}`
![image](https://user-images.githubusercontent.com/52304443/68069904-f67f8a80-fd77-11e9-90f0-02bb271711cd.png)

https://github.com/CodaProtocol/coda-python-client/blob/51ea0745913c5dc89ee84101a68e0367bb754bf4/CodaClient.py#L79
Change ` if response.status_code == 200:` to `if response.status_code == 200 and '"errors":' not in response.text:`

**Comment by yourbuddyconner** [comment]
Thanks @c29r3 I will take care of this ASAP
